<?php

class ValidClass
{
    function validFunction() {return;}
    function validFunction2() {return;}
    function validFunction3() {return;}
    function validFunction4() {return;}
    function validFunction5() {return;}
    function validFunction6() {return;}
    function validFunction7() {return;}
    function validFunction8() {return;}
    function validFunction9() {return;}
    function validFunction10() {return;}
    function validFunction11() {return;}
    function validFunction12() {return;}
    function validFunction13() {return;}
    function validFunction14() {return;}
}

class InValidClass
{
    function validFunction() {return;}
    function validFunction2() {return;}
    function validFunction3() {return;}
    function validFunction4() {return;}
    function validFunction5() {return;}
    function validFunction6() {return;}
    function validFunction7() {return;}
    function validFunction8() {return;}
    function validFunction9() {return;}
    function validFunction10() {return;}
    function validFunction11() {return;}
    function validFunction12() {return;}
    function validFunction13() {return;}
    function validFunction14() {return;}
    function validFunction15() {return;}
    function validFunction16() {return;}
}
