<?php
function validFunctionOfFourteenLines()
{
    echo '';

    echo '';
    echo '';
    echo '';

    echo '';
    echo '';
    echo '';

    echo '';

    echo '';
    echo '';
    echo '';

    return;
}

function invalidFunctionOfSixteenLines()
{
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';

    return;
}
