<?php
function validFunctionOfFourteenLines()
{
    echo '';

    echo '';
    echo '';
    echo '';

    echo '';
    echo '';
    echo '';

    echo '';

    echo '';
    echo '';
    echo '';

    return;
}

function invalidFunctionOfSixteenLines()
{
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';
    echo '';

    return;
}

function validFunctionOfSixteenCodeLines()
{
    echo '';

    //Comment
    echo '';

    echo '';
    echo '';

    /* Comment */
    echo '';


    echo '';
    echo '';

    /** @var Comment */
    echo '';

    echo '';


    /**
     * @var Comment
     */
    echo '';
    echo '';

    return;
}
